### ISSUE TITLE
why python2 only?

### ISSUE THREAD

**Issue by wonko21** [grindsa/dkb-robo#1]
Hi,
you are using mechanize an python2 only lib.
Python 2 will be eol in 2 years: https://www.python.org/dev/peps/pep-0373/#update

Maybe switch to https://mechanicalsoup.readthedocs.io/en/stable/ ?

I was just starting to write a dkb2influxdb script (grafana dash for dkb ;-) ) 

cu
Chris

**Comment by grindsa** [comment]
Hi Chris,

thanks for your comment. Thats exactly the reason why I published the library on github. Let me have a look into it.

/GrindSa

**Comment by grindsa** [comment]
Hi Chris,

try [v0.6](https://github.com/grindsa/dkb-robo/releases/tag/0.6) and let me know your feedback.

/GrindSa

**Comment by wonko21** [comment]
Works!
