### ISSUE TITLE
Display full transaction information

### ISSUE THREAD

**Issue by james-woods** [grindsa/dkb-robo#10]
When querying transactions and getting them as a list, only the abbreviated text is returned. It would be helpful to provide the possibility to query the extended information (the stuff you get when clicking the magnifier symbol next to it in the web interface).

**Comment by grindsa** [comment]
Hi James,

check the latest commit in devel-branch https://github.com/grindsa/dkb-robo/commit/72edf7554ff40c5c0279e81f401ba2e6654d9b1c. Transactions will contain the information from CSV file.

Have a nice day.
G

**Comment by grindsa** [comment]
check https://github.com/grindsa/dkb-robo/issues/11 

/Gs
