### ISSUE TITLE
dkb_robo does not work due to MFA feature introduced by Deutsche Kreditbank

### ISSUE THREAD

**Issue by timakro** [grindsa/dkb-robo#15]
I fear javascript is now required. I tried my luck but didn't get it to work (and got locked out of my account -- they seem to lock your account when you generate a lot of TANs but don't use them, keep that in mind when testing). Let me know when you figure something out :)

**Comment by grindsa** [comment]
I am aware of the issue.. I am already in contact with DKB but the discussion is not easy. Give me a couple of days to think about alternate optins. Will keep you posted...

/Grindsa

**Comment by leoc** [comment]
Hey grindsa, I am the developer of https://github.com/leoc/ledgit and wondered, too, how to adjust the login procedure. 

How is the communication with DKB going? And would it make sense to chime in as open-source developer for more leverage?

**Comment by alacambra** [comment]
Some progress on this issue? I am facing the same issue. Have realised that actually exists an API, PSD2. I am checking if that could be a suitable solution. Do you know it?

**Comment by grindsa** [comment]
Hi, unfortunately no progress at all. DKB stopped replying to my emails. Do you have some further information on the API you are referring to?

**Comment by kain88-de** [comment]
I do not think you can achieve much with PSD2 as a private user.  There is the Fin-TS standard for private users in Germany (python implementation [here](https://github.com/raphaelm/python-fints)), but that does not cover credit cards for the DKB. I wrote myself now a selenium script that downloads the files for me.

**Comment by leoc** [comment]
@kain88-de Very nice, how do you work around the pushtan login automatically

**Comment by kain88-de** [comment]
I did not work around it. Selenium allows you to codify navigation on a
webpage in a real browser. So once I hit the push tan the script stops and
waits for me to enter the tan. Afterwards everything is automated again.

I tried to achieve the same behavior with the initial code
 Mechanicalsoup doesn’t interpret the website in a way that allows me to
submit the push tan request ( I have two devices setup).

**Comment by grindsa** [comment]
Python-fints does not really work well, however I pushed some changes to the devel-branch that DKBRobo handle is able to handle the confirmation via DKB-app. So after login DKBrobo will wait for the confirmation via app and  continue to fetch account information and transactions.  Selenium is not required. Give it a try and let me know if it works. But please handle with care; I cannot predict what happens if you do not confirm the login. I will implement proper error handling in the upcoming days (need 2nd account to login first).

**Comment by grindsa** [comment]
Closing the issue. Starting from v0.9 dkb-robo does support the mfa login procedures.
