### ISSUE TITLE
Some Unit Tests

### ISSUE THREAD

**Issue by wonko21** [grindsa/dkb-robo#2]
Hi lets write some unit tests. I might find some time later this week or on the weekend

**Comment by grindsa** [comment]
Hi, Sounds like a good plan. I am not really familar with unit testing (i am not a professional developer) however it seems I can learn someting. Will start some investingation to get familar with the topic as such.

/GrindSa

**Comment by wonko21** [comment]
If I find some time on the weekend I can add some basic ones.

**Comment by grindsa** [comment]
Hi, thanks. I added additional ones based on your skeleton...
