### ISSUE TITLE
dkb-robo fails when the new "DKB" app is used to confirm login

### ISSUE THREAD

**Issue by dewulf** [grindsa/dkb-robo#24]
Response for poll on
poll_url = self.base_url + '/DkbTransactionBanking/content/LoginWithBoundDevice/LoginWithBoundDeviceProcess/confirmLogin.xhtml'
returns 500 and for this the .json() method fails.

Here the trace:
DKBRobo.login()

DKBRobo.new_instance()

Starting new HTTPS connection (1): www.dkb.de
https://www.dkb.de:443 "GET /banking HTTP/1.1" 200 None
https://www.dkb.de:443 "POST /banking HTTP/1.1" 200 None
DKBRobo.login_confirm()

check your banking app and confirm login...
https://www.dkb.de:443 "GET /DkbTransactionBanking/content/LoginWithBoundDevice/LoginWithBoundDeviceProcess/confirmLogin.xhtml?$event=pollingVerification&_=0 HTTP/1.1" 500 21563
Traceback (most recent call last):
  File "./dkb.py", line 14, in <module>
    with DKBRobo('xxxxxxxx', 'xxxxxx', False, True) as dkb:
  File "/home/daniel/.local/lib/python3.6/site-packages/dkb_robo/dkb_robo.py", line 89, in __enter__
    self.login()
  File "/home/daniel/.local/lib/python3.6/site-packages/dkb_robo/dkb_robo.py", line 521, in login
    login_confirmed = self.login_confirm()
  File "/home/daniel/.local/lib/python3.6/site-packages/dkb_robo/dkb_robo.py", line 611, in login_confirm
    result = response.json()
  File "/home/daniel/.local/lib/python3.6/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by grindsa** [comment]
Is this a permanent issue or rather a kind of one-off? I am asking as i am not able to replicate it on my side.

Which dkb-robo version are you using in your environment?

**Comment by dewulf** [comment]
Thanks for your answer.
I'm using the latest version 0.11
I assume that it is related to the confirmation app, that I use on my telephone. I recently updated to the latest DKB app (version 1.4 from 29.11.2021). Before I used a somehow older version of it.

**Comment by grindsa** [comment]
Sorry for me its still not fully clear what is going on.
What I understood is that this is a permanent issue starting after you upgraded the DKB app. Is this correct? 

Further it is a bid surprising that there is a dependency to the DKB banking app. I did also check the app-versions in Google-Playstore and Apple-App Store. The latest versions provided there are 3.12.0 which is different from what you specified above.

Which app are you using on which OS?

**Comment by dewulf** [comment]
Excuse for my late answer but I see you already could replicate the issue. Then it really seems to be the new DKB-APP. Thanks for fixing it

**Comment by grindsa** [comment]
I pushed a couple of changes to [devel branch](https://github.com/grindsa/dkb-robo/tree/devel) to support the new DKB-APP. Please give it a try and let me know if it works for you.

**Comment by dewulf** [comment]
Works like a charm)) thanks a lot!
