### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by muescha** [grindsa/dkb-robo#30]
i executed the example doc_downloads with archive and download all:

```python
> document_dic = dkb.scan_postbox(path, True, True)
```

i got this error:

```bash
Writing documents to /Users/muescha/Documents/DKB/
Traceback (most recent call last):
  File "/Users/muescha/Work/github.com/grindsa/dkb-robo/dkb_docdownload.py", line 35, in <module>
    POSTBOX_DIC = dkb.scan_postbox(PATH,True,True)
  File "/Users/muescha/Work/github.com/grindsa/dkb-robo/dkb_robo/dkb_robo.py", line 964, in scan_postbox
    pb_dic[link_name]['documents'] = self._get_document_links(pb_dic[link_name]['details'], path, link_name, select_all)
  File "/Users/muescha/Work/github.com/grindsa/dkb-robo/dkb_robo/dkb_robo.py", line 225, in _get_document_links
    table = soup.find('table', attrs={'class': 'widget widget abaxx-table expandableTable expandableTable-with-sort'})
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by grindsa** [comment]
are you getting this error every time you are trying to run the script or was this rather a one-timer?

**Comment by muescha** [comment]
Sorry - I run the script only one time. I did not run it twice. 

I checked and I think the script downloaded all files.

**Comment by grindsa** [comment]
I pushed some improvements into [v0.17](https://github.com/grindsa/dkb-robo/releases/tag/0.17). Its pretty difficult to test as we are addressing rather a corner case which is not happening all the time. Let me know in case it does not work for you.

**Comment by muescha** [comment]
Thx for the fast fix. 

The DKB Account is cancelled so i can not test anymore.
