### ISSUE TITLE
Double Name - only one downloaded

### ISSUE THREAD

**Issue by muescha** [grindsa/dkb-robo#31]
i have in archive in messages 5 file with name `Informationsbogen zur Einlagensicherung`

i used this command to download all files:
```python
> document_dic = dkb.scan_postbox(path, True, True)
```

as result i get only one document downloaded.

with same name it should have a incrementing counter

**Comment by grindsa** [comment]
I never thought about such a scenario. But anyway your proposal makes perfect sense. Let me work on it.

**Comment by grindsa** [comment]
The improvement made it into [v0.17](https://github.com/grindsa/dkb-robo/releases/tag/0.17). From now on a timestamp will be added to the filename to avoid overrides in case of duplicate filenames.
