### ISSUE TITLE
Question regarding startdate and entdate 

### ISSUE THREAD

**Issue by fischmir** [grindsa/dkb-robo#37]
Hi,

I have a question regarding this part from the documentation:

**date_from - start date in European notation (DD.MM.YYYY)
date_to - end date in European notation (DD.MM.YYYY)**

=> Are these related used for the the column **bdate** or **vdate**?

Thanks for clarification.
Christian

**Comment by grindsa** [comment]
Hi,

this is actually a good question. "date_from" and "date_to" dates are being submitted as part of the html form so the filtering of the transactions is done by DKB. But I played around; it seems to be bdate.

bdate = booking date - Buchungstag
vdate = valuation date - Wertstellung

HTH
GrindSa
