### ISSUE TITLE
PSD2 API Solution - CREALOGiX

### ISSUE THREAD

**Issue by AbdoCherry** [grindsa/dkb-robo#40]
Hi all, Hallo zusammen,

I was searching for alternatives which are similar with Comdirect API Key Functionality where you can sign in with a bearer token (oauth2) and collect your own transaction informations like all activities and other valuable informations.

What I've found was a similar solution offered by a partner of DKB named "CREALOGix" and I'll try to build for myself a python-backend to collect my personal (non-commercial) financial informations to track them more automatically.

Why I'm writing this, maybe some of you or maybe @grindsa you have some hints which you can share or maybe contribute to build a personal Application. Of course it is not for commercial use in big and wide scale for consumers, because you have to organise your own keys and manage them into the python-script / config.ini / environment Variables. 

I've attached the official documentation and sorry for abusing your issue tracking list for insisting an extending alternative to your great work. By the way I'm working with your library for a while and it is great. I also follow you 👍🏼 

Best regards and have a nice Sunday,
Abda
[PSD2 API Solution DKB - Documentation for TPPs v1.0.pdf](https://github.com/grindsa/dkb-robo/files/11782410/PSD2.API.Solution.-.Documentation.for.TPPs.v1.0.pdf)

**Comment by grindsa** [comment]
i do not have issues to talk about external alternatives. 
That you are trying to achieve is already possible.  The new DKB frontend uses a rest-server as backend and authenticates via bearer token after completing the 2FA successfully.  Check the [_login method](https://github.com/grindsa/dkb-robo/blob/master/dkb_robo/dkb_robo.py#L663) in the library.

I am not a fan of API-providers but this is a rather personal opinion. Maybe I am just jealous as these guys get access without issues while i got blocked by DKB for years and had to reverse-engineer the endpoints myself.
