### ISSUE TITLE
Please release the recent changes, dkb.account_dic is empty since 11.07.2023 with legacy login=True

### ISSUE THREAD

**Issue by nkuttler** [grindsa/dkb-robo#41]
Not sure if this is a problem on my end, or if it's related to #39 and maybe something old was disabled? Can anybody confirm?

**Comment by tj0vtj0v** [comment]
Hi, I got the same problem this noon.
I resolved it by updating the library, but so far I just tested it in the IDE.

**Comment by nkuttler** [comment]
@tj0vtj0v  Which library?

**Comment by tj0vtj0v** [comment]
@nkuttler the whole dkb-robo lib.
in the traceback there was only a error with the MechanicalSoup mentioned but I think this refers to the changes from #39

**Comment by nkuttler** [comment]
Ok, seems like the fix is the change in https://github.com/grindsa/dkb-robo/commit/cae857fbdd26a6d14f43df2eb969e8a2a565e793, so setting legacy_login=False. Seems like a new release would be useful.

**Comment by grindsa** [comment]
there were some URL changes at DKB site which are fixed in a91d0d4841092c0e38803a021d4e8a3de939db41. New release [v0.22](https://github.com/grindsa/dkb-robo/releases/tag/0.22) got just published.

**Comment by grindsa** [comment]
Seems the library works without issues. I will start migrating the different methods. over the next view weeks and ensure a certain level of backwards compatibility. Will keep you guys posted...
