### ISSUE TITLE
migration to the new DKB frontend

### ISSUE THREAD

**Issue by grindsa** [grindsa/dkb-robo#42]
# migration status

- DKBRobo.account_dic() - :white_check_mark: - released with 0.23
- DKBRobo.get_credit_limits() - :white_check_mark: - released with 0.25
- DKBRobo.get_exemption_order()- :x:
- DKBRobo.get_points() - :x:
- DKBRobo.get_standing_orders()) - :white_check_mark: - released with 0.25
- DKBRobo.get_transactions()-:white_check_mark: - released with 0.23
- DKBRobo.last_login- :x:
- DKBRobo.login() - :white_check_mark: - released with 0.22
- DKBRobo.scan_postbox - :white_check_mark: - released with 0.25

# breaking changes when migrating to the new frontend:

I am trying to ensure a certain level of backwards compatibility however there are a few changes you need to be aware when migrating to the new frontend.

## general
- default date format is changed to `%Y-%m-%d`

## DKBRobo.account_dic()

- account ordering is based on the new frontend
- debit cards are shown in overview
- IBANs are now represented without spaces
- card numbers are masked
- product groups (taken from UI) are shown in account overview
- additional account attributes (currency code, limit)
- additional card attributes (holder-name, status, expiry date)

## DKBRobo.get_standing_orders()
-  account_dic[x]['id'] must be specified as input
-  data-structure changed (`interval` subtree added)

## DKBRobo.get_transactions()

- "mandatreferenz" and "customerreferenz" attributes will only be shown if available

## DKBRobo.scan_postbox()
- the document list provided in via API larger than shown in UI
- so far only documents from categories "Kontoauszüge" and "Kreditabrechnungen" provided via API

**Comment by larmeh** [comment]
Would it be a good idea to keep supporting the old banking until it becomes unavailable? If so, adding subdomain "ib" to the old base URL is sufficient.

**Comment by grindsa** [comment]
The old frontend will be supported as long it is available.  The plan is to use the `legacy_login` parameter switch between old and new frontend. I will also try to keep method names inside the `DKBRobo()` class the same. There might be some smaller changes (f.iiorder of accounts and cards in `dkb.account_dic`)  but overall look and feel should stay more or less similar.

**Comment by grindsa** [comment]
@larmeh  i am progressing to migrate the old methods to the new API. 

Would it be ok to give dates in a different format `YYY-MM-DD`  than currently (`DD.MM.YYYY`) or will this cause problems on your side?

**Comment by larmeh** [comment]
@grindsa Sure, as a matter of fact, I even convert the dates to that format currently.

**Comment by grindsa** [comment]
closing as the old frontend got removed from library in [v0.27](https://github.com/grindsa/dkb-robo/releases/tag/0.27)
