### ISSUE TITLE
Changing information

### ISSUE THREAD

**Issue by ralpho1337** [grindsa/dkb-robo#43]
Hi all,

I'm getting transformation with your great library and having issues getting unique information: sometimes a few days later, the text of the transaction, the type and also the partner changes some information. e.g. the partner is shown just with the name the first day, a few days later i get the partner with address on the next day. Also the transaction type changes.

Do you guys also observe this behaviour? Do you have mitigations measures identified to uniquely identify a transaction?

Best
Ralph

**Comment by grindsa** [comment]
Hi,

sorry for keeping you waiting but I was on holidays.  I cannot confirm the issue you are observing but this does not mean that it's not there :-). Are you referring to account or credit-card transactions?

DKBRobo is not doing fancy things here. It is just downloading the csv file from the DKB portal and parse the content line by line. So an update of the records by DKB could lead to the behavior you are seeing.

Can you start troubleshooting the issue on your side by downloading the CSV file day by day and compare it with the older versions as well as the output you are getting from DKBRobo?

**Comment by grindsa** [comment]
c.losing due to inactivity
