### ISSUE TITLE
Update doc/dkb_example.py with new parameters

### ISSUE THREAD

**Issue by fischmir** [grindsa/dkb-robo#44]
Hi,

I updated to the latest version, but it doesn't work as I expect.

However - as I am a copy&paste programmer :D -  I checked the example to check, if I am doing somehting wrong, but I assume the current parameters are not part of the dkb_example.py

I am wondering, if the current example is working with the latest version...?

Regards
Christian

**Comment by grindsa** [comment]
Hi,

i tested this morning and could get it working without issues. Which error are you getting?

BR G.

**Comment by fischmir** [comment]
My password was not correct- sorry, my fault.
