### ISSUE TITLE
Mandatsreferenz missing

### ISSUE THREAD

**Issue by robbeofficial** [grindsa/dkb-robo#49]
Ticket #11 mentions a 'mandatsreferenz' field in the data but it is missing when I fetch using v0.24. Maybe something changed with the naming of the CSV? When I manually fetch a CSV from the website, it contains a "Mandatsreferenz" column.

**Comment by grindsa** [comment]
Tanks for pointing this out. Indeed, something has changed.

There is a field `mandateId` containing the Mandatsreferenz. I will create a fix in the upcoming days

**Comment by grindsa** [comment]
Hi,

fix got slotted into [0.24.1](https://github.com/grindsa/dkb-robo/releases/tag/0.24.1). 

Please check if it works for you...

**Comment by robbeofficial** [comment]
Thanks for the fast fix, works like a charm! 

This change only introduces a slight inconsistency in field naming: "mandatereference" vs. "customerreferenz" but that's just a minor issue.

**Comment by grindsa** [comment]
thanks for confirming the fix and for highlighting the inconsistency. This is a day 1 issue which is in since several years.  I will fix it with the next release and will close this issue...
