### ISSUE TITLE
Code refactoring for easier audit

### ISSUE THREAD

**Issue by Parrot7483** [grindsa/dkb-robo#50]
**Description:**
In the process of reviewing the monolithic Python code, I encountered unnecessary complexity that hindered the understanding of the code.

**Proposed Changes:**
1. **Code Modularization**: Split code into separate files. Uppon my uderstanding a split into the legacy API, new API, and utility functions would be a good first step. 
   
2. **Type Hints**: Introduce type hints for function headers.

**Benefits:**
- **Improved Auditability**: Easier review of specific components for enhanced security.
- **Enhanced Readability**: Improved overall readability and maintainability.
  
- **Type Safety**: Clearer documentation of expected input/output types.

**PS:**
Thank you for creating and maintaining this library. I'm grateful for the existence of such a helpful tool. Your work is highly appreciated!

**Comment by grindsa** [comment]
Thank you for your feedback. What you are proposing makes absolute sense. But this requires some effort so it's rather a midterm exercise...

**Comment by grindsa** [comment]
Quick update:  I pushed a couple of changes into the [devel](https://github.com/grindsa/dkb-robo/tree/devel) branch.

- code has been separated as suggested
- type hints had been added

Feel free to have look. Feedback is always welcome...

**Comment by grindsa** [comment]
Improvements got included in [v0.25](https://github.com/grindsa/dkb-robo/releases/tag/0.25). Thus I am closing the issue...

**Comment by Parrot7483** [comment]
Just had a look at the new structure. Great work!
