### ISSUE TITLE
Recommendation: Switch to Poetry instead of relying on setup and requirements.txt

### ISSUE THREAD

**Issue by DominikRoB** [grindsa/dkb-robo#51]
See title. 
I think more and more (including PEP, see https://peps.python.org/pep-0517/) recommendations point toward the us of pyproject.toml. I think poetry is an easy way to be compliant with PEP-517.

**Comment by angelo-peronio** [comment]
@grindsa if desired, I can (slowly) prepare a PR to replace `setup.py` and `requirements.txt` with a new, shiny, future-ready `pyproject.toml`. I would *not* include Poetry, since I have no experience with it.

**Comment by grindsa** [comment]
PRs are always welcome...

**Comment by grindsa** [comment]
Changes made it into [v0.28](https://github.com/grindsa/dkb-robo/releases/tag/0.28). Hence, closing this issue
