### ISSUE TITLE
Amount for an account for a given date

### ISSUE THREAD

**Issue by adegenkolbe** [grindsa/dkb-robo#54]
Hi,

is there a way to get the amount of an account for a given date ?
In the old interface you can filter your transactions for given time period and see the amount for this.
When you export these results as csv you also see your amount.

Would be great to get this feature.

Thanks for your work and kind regards
Andy

**Comment by grindsa** [comment]
Hi,

just for clarification and to avoid misunderstandings. You would like to see the "Tagessaldo" of an account for a certain date, right?

If so this will be a challenge as the new backend does not hold this information. This would mean that we need to calculate backwards from the current date. and amount..

I am not saying that it is impossible. Give me a few days to think about it more in detail...

BR G.

**Comment by adegenkolbe** [comment]
Hi,

this is exactly what I mean.

Just to explain what i want to do:

Would like to use dkb-robo to fill my "Haushaltsbuch". 
For now i used the CVS Export of the old Web-Interface to track my transactions.
On the first of every month i used the export for the month before (eg. on March 1 i would export the transactions for Feb 1 to Feb. 29).

I import all the transactions into an excel sheet for some analytics.
Sometimes not all the transactions were in the transaction list (maybe they were not booked), but the were already taken into account  in the saldo.

To have a check for this, i use the "Tagessaldo" from the export (which is then the saldo of the last day of this export), add the sum of  the amount of the transactions from the list and then i should have the "Tagessaldo" of the month before last month( hope you understand).

So if the new API did not offer this information right now, is there a i way i can get it with the old one ?
Because calculating the value should be the same as i do already in the excel sheet. So if there is a transaction missing, it would not be detected.

**Comment by grindsa** [comment]
The DKB REST-API currently lacks "Tagessaldo" values, and the previous method for accessing them has been deactivated. Consequently, you will need to calculate this information manually.

Apologies for any inconvenience this may cause.

Sorry
/G.
