### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Stelzerfe** [grindsa/dkb-robo#55]
Hey i'm not too familiar with coding but i like this one and find it very useful. At one point, everything worked quiet well but since couple of weeks i get the error "Login failed: LinkNotFoundError". 

I#m using python 3.9 on anaconda. 

Thanks a lot.

**Comment by grindsa** [comment]
Hi,

which dkb_robo version are you using?

Can you please enable debugging as below and share the logs?

```
with DKBRobo(dkb_user=DKB_USER, dkb_password=DKB_PASSWORD, debug=True,) as dkb:
        pprint(dkb.account_dic)
```

You can also share the logs via email at  grindelsack <at> gmail.com

/G.

**Comment by grindsa** [comment]
you are using a very old version and I supposed that you are affected a91d0d4841092c0e38803a021d4e8a3de939db41. I suggest to update to the latest release which is [v0.26](https://github.com/grindsa/dkb-robo/releases)

**Comment by Stelzerfe** [comment]
yeah thanks i could have figured out that myself. It works now. Have a good one
