### ISSUE TITLE
How to set path for document download?

### ISSUE THREAD

**Issue by Coxeroni** [grindsa/dkb-robo#57]
My python skills are more or less zero and I couldn't get the dkb_docdownload.py to work as I simply could not set a path because I don't know how 😉
The error was always "no path given".

If somebody would be so kind to explain this to me, I would be very grateful.

**Comment by grindsa** [comment]
[dkb_docdownload.py](https://github.com/grindsa/dkb-robo/blob/master/doc/dkb_docdownload.py) stored in [doc](https://github.com/grindsa/dkb-robo/tree/master/doc) contains a download example. Just add dkb-user and password and call the script like below

```bash
python3 dkb_docdownload.py documents
```

I will try to extend the [CLI](https://github.com/grindsa/dkb-robo/tree/master/doc) with the capabilities to download documents but this will take a couple of days.

**Comment by Coxeroni** [comment]
Thanks for your help. So this was easier than I thought, either it was an issue with Windows python I was initially using or I stumbled over my own feet.

Is the "documents" after dkb_docdownload.py the actual path? At least now the script downloads my new docs to the documents sub-folder, which makes me happy 😁
