### ISSUE TITLE
Brokerage account transactions do not deliver all attributes

### ISSUE THREAD

**Issue by usaerc** [grindsa/dkb-robo#62]
When I run the script, I do not get the following attributes for transactions in brokerage accounts: currencycode: ,  'isin_wkn':,  'market': ,  'price':,   'text': 

Any advice, why this may be?

**Comment by grindsa** [comment]
I pushed some changes into a [separate branch](https://github.com/grindsa/dkb-robo/tree/brokerage) which should hopefully fix your issue. Pls try and let me know.

Thx G.

**Comment by usaerc** [comment]
Thank you very much. The issue is fixed and I see all attributes.
Not sure if this is related, but I see there is the error "api.Wrapper._build_product_display_settings_dic(): "name" key not found"

**Comment by grindsa** [comment]
Thank you for confirming.  The error message is not related to the problem you observed and can be ignored.  It seems that DKB did change the data structure with one of their update.  I will remove the warning in the next release.

**Comment by grindsa** [comment]
fixes made it into [v0.28](https://github.com/grindsa/dkb-robo/releases/tag/0.28). Hence, closing this issue.
